### ISSUE TITLE
Support on Pentaho Data Integration 6.x

### ISSUE THREAD

**Issue by dobeslao** [legsem/legstar-pdi#19]
Is there any plan for bring your excellent plugin to working over version 6.x of Pentaho Data Integration?

When i try to install from Pentaho MarketPlace i get the following message:

> Error occurred when installing plugin LegStar z/OS File reader Plugin.[ Invalid Plugin Id.]

If i try to put the plugins/steps folder from previous version, the objects on transformation shows well, but if i try to run, get the errors below.

Any info about the roadmap of the plugin will be appreciated.

> 2016/04/22 16:40:10 - z/OS File Input.0 - Using COBOL-annotated JAXB class 'z_002fosfileinput.cusdatcc.CustomerData[z_002fosfileinput.cusdatcc.jar]'
> 2016/04/22 16:40:20 - z/OS File Input.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : Unexpected error
> 2016/04/22 16:40:20 - z/OS File Input.0 - ERROR (version 6.0.1.0-386, build 1 from 2015-12-03 11.37.25 by buildguy) : java.lang.NoClassDefFoundError: org/apache/commons/vfs/FileSystemException
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at com.legstar.pdi.zosfile.ZosFileInput.processRow(ZosFileInput.java:122)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.lang.Thread.run(Thread.java:745)
> 2016/04/22 16:40:20 - z/OS File Input.0 - Caused by: java.lang.ClassNotFoundException: org.apache.commons.vfs.FileSystemException
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.security.AccessController.doPrivileged(Native Method)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
> 2016/04/22 16:40:20 - z/OS File Input.0 -     ... 3 more

Regards.

**Comment by raghuhebbar** [comment]
Having the same issue. Is there a plan to make the plugin compatible with 6.0 and Java 1.7/1.8 ?

**Comment by andrewmoses** [comment]
So, it is cause of compatibility issue. Can I at least know which PDI version is compatible with this plugin ?
